app/Http/routes.php
<?php

// auth
Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'login']);
Route::post('/login/store', 'AuthController@loginStore')->name('auth.login.store');
Route::get('/register', 'AuthController@register');
Route::post('/register/store', 'AuthController@registerStore')->name('auth.register.store');
Route::get('/logout', 'AuthController@logout');

// main and home
Route::get('/', ['uses' => 'MainController@index', 'as' => 'main']);
Route::get('/home/{id}', ['uses' => 'HomeController@index']);

// profile setting
Route::get('/editprofile', ['uses' => 'ProfileController@edit', 'as' => 'editprofile']);
Route::post('/editprofile/store', 'ProfileController@editStore')->name('profile.edit.store');
Route::post('/changepassword/store', 'ProfileController@changePassword')->name('profile.changepassword.store');
Route::get('/accountsetting', ['uses' => 'ProfileController@accountsetting', 'as' => 'accountsetting']);
Route::post('/accountsetting/store', 'ProfileController@accountsettingStore')->name('profile.accountsetting.store');

// post
Route::get('/my_post/{user_id}', ['uses' => 'PostController@mypost']);
Route::get('/post/{id}', ['uses' => 'PostController@index']);
Route::get('/edit_post/{statuses_id}', ['uses' => 'PostController@editpost']);
Route::get('/delete_post/{statuses_id}', ['uses' => 'PostController@deletepost']);
Route::post('/edit_post/store', 'PostController@editStore')->name('post.edit.store');

// status
Route::get('/status/like', 'StatusController@likeStore')->name('status.like.store');
Route::post('/status/store', 'StatusController@postStore')->name('status.post.store');
Route::post('/status/comment', 'StatusController@commentStore')->name('status.comment.store');

// notification
Route::get('/notification', 'NotificationController@index');

// not found page
Route::get('/not-found', function () {
    return view('errors.404');
});

app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Support\Str;

class Status extends Model implements AuthenticatableContract,
    AuthorizableContract

{
    use SoftDeletes;
    use Authenticatable, Authorizable;

    CONST STATUS_ACTIVE = 1;

    protected $table = 'statuses';

    protected $fillable = [
        'user_id',
        'parent_id',
        'body',
        'status',
    ];

    protected $appends = [
        'publish_at',
        'count_like'
    ];

    protected $hidden = [
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function parent()
    {
        return $this->belongsTo(Status::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Status::class, 'parent_id');
    }

    public function likeable()
    {
//        return $this->belongsTo(Likeable::class, 'id', 'statuses_id');
        return $this->belongsTo(Likeable::class, 'id', 'statuses_id');
    }

    public function getPublishAtAttribute()
    {
        return date("F, j Y H:i", strtotime($this->attributes['created_at']));
    }

    public function getHasLikeAttribute()
    {
        $likeable = Likeable::selectRaw("type")->where("statuses_id",$this->attributes['id'])->where("user_id",$_SESSION['id'])->where("type",1)->first();
        return (!empty($likeable)) ? $likeable->type : 2 ;
    }

    public function getCountLikeAttribute()
    {
        $likeable = Likeable::selectRaw("count(id) as count_like")->where("statuses_id",$this->attributes['id'])->where("type",1)->first();
        return $likeable->count_like;
    }

    public function getCountViewAttribute()
    {
        $visitable = Visitable::selectRaw("sum(count) as count_view")->where("statuses_id",$this->attributes['id'])->where("type",1)->first();
        return $visitable->count_view;
    }

    public function getBodyLimit20Attribute()
    {
        return Str::words($this->attributes['body'], '20');
    }

    public function getBodyLimit100Attribute()
    {
        return Str::words($this->attributes['body'], '100');
    }

    public function getCommentLimitAttribute()
    {
        $status = Status::select('statuses.*', 'users.image')
            ->where("statuses.parent_id",$this->attributes['id'])
            ->join('users', 'users.id', '=', 'user_id')
            ->orderBy("statuses.created_at","asc")
            ->take(3)
            ->get();
        return $status;
    }

    public function getCommentsAttribute()
    {
        $status = Status::select('statuses.*', 'users.image')
            ->where("statuses.parent_id",$this->attributes['id'])
            ->join('users', 'users.id', '=', 'user_id')
            ->orderBy("statuses.created_at","asc")
            ->get();
        return $status;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use App\Models\Status;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;


class User extends Model implements AuthenticatableContract,
    AuthorizableContract

{
    use Authenticatable, Authorizable;


    CONST LOGIN = true;
    CONST NOT_LOGIN = false;
    CONST STATUS_ACTIVE = 1;
    CONST NOT_ANONIM = 2;
    CONST IS_ANONIM = 1;

    protected $table = 'users';


    protected $fillable = [
        'username',
        'email',
        'password',
        'first_name',
        'last_name',
        'status',
        'is_anonim',
        'gender',
        'mobile',
        'image',
        'birth'
    ];


    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function getName()
    {
        if ($this->first_name && $this->last_name) {
            return "{$this->first_name} {$this->last_name}";
        }

        if ($this->first_name) {
            return $this->first_name;
        }

        return null;
    }

    public function getNameOrUsername()
    {
        return $this->getName() ?: $this->username;
    }

    public function getFirstNameOrUsername()
    {
        return $this->first_name ?: $this->username;
    }


    public function getAnonimNameAttribute()
    {
        return substr($this->first_name,0,3);
    }
}

resources/views/content/accountsetting.blade.php
<div class="central-meta">
    <div class="onoff-options">
        <h5 class="f-title"><i class="ti-settings"></i>account setting</h5>
        @if(Session::get('success_accountsetting'))
            @include('_partials.notifications')
        @endif
        <form method="post" role="form" action="{{ route('profile.accountsetting.store') }}">
            <div class="setting-row">
                <span>Enable Anonymouss</span>
                <p>You'll become anonymous.</p>
                <input type="checkbox" name="is_anonim" {{ ($users->is_anonim == 1) ? "checked" : "" }} id="switch"/>
                <label for="switch" data-on-label="ON" data-off-label="OFF"></label>
            </div>
            <div class="submit-btns">
                <button type="submit" class="mtr-btn"><span>Save</span></button>
            </div>
            <input type="hidden" name="_token" value="{{ Session::token() }}">
            <input type="hidden" name="id" value="{{ $users->id }}">
        </form>
    </div>
</div>

resources/views/content/changepassword.blade.php
<div class="central-meta">
    <div class="editing-info">
        <h5 class="f-title"><i class="ti-lock"></i>Change Password.</h5>
        @if(Session::get('danger_changepassword'))
            @include('_partials.notifications')
        @endif
        @if(Session::get('success_changepassword'))
            @include('_partials.notifications')
        @endif
        <form method="post" role="form" action="{{ route('profile.changepassword.store') }}">
            <div class="form-group">
                <input type="password" name="current_password" required="required"/>
                <label class="control-label" for="input">Current password</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="password" id="input" name="new_password" required="required"/>
                <label class="control-label" for="input">New password</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="password" name="confirm_password" required="required"/>
                <label class="control-label" for="input">Confirm password</label><i class="mtrl-select"></i>
            </div>
            <div class="submit-btns">
                <button type="submit" class="mtr-btn"><span>Save</span></button>
            </div>
            <input type="hidden" name="_token" value="{{ Session::token() }}">
            <input type="hidden" name="id" value="{{ $users->id }}">
        </form>
    </div>
</div>

resources/views/content/countpost.blade.php
<div class="widget">
    <h4 class="widget-title">Post</h4>
    <ul class="short-profile">
        <li>
            <a href="{{URL::to('/my_post/'.base64_encode($session['id']))}}"><span class="pointing">All ({{$count_post['all']}})</span></a>
        </li>
        <li>
            <a href="{{URL::to('/my_post/'.base64_encode($session['id'])."?status=2")}}"><span class="pointing">Unpublish ({{$count_post['draft']}})</span></a>
        </li>
        <li>
            <a href="{{URL::to('/my_post/'.base64_encode($session['id'])."?status=1")}}"><span class="pointing">Publish ({{$count_post['publish']}})</span></a>
        </li>
    </ul>
</div>

resources/views/content/detailpost.blade.php
@foreach($list_post as $post)
    <div class="central-meta item">
        <div class="user-post">
            <div class="friend-info">
                <figure>
                    @if (!empty($post->image))
                        <img src="{{URL::to("../public/images/".$post->image)}}" alt="" style="width:60px; height:60px;">
                    @else
                        <img src="{{URL::to("../resources/assets/images/resources/img_user_default.jpg")}}" alt=""
                             style="width:60px; height:60px;">
                    @endif
                </figure>
                <div class="friend-name">
                    @if ($post->user->is_anonim == 1)
                        <ins><a title="">{{$post->user->anonim_name}}*****</a></ins>
                    @else
                        <ins><a title="">{{$post->user->first_name}} {{$post->user->last_name}}</a></ins>
                    @endif
                    <span>published: {{$post->publish_at}}</span>
                </div>
                <div class="post-meta">

                    <div class="description">
                        <p>
                            {!! nl2br(htmlspecialchars_decode(stripslashes($post->body))) !!}
                        </p>
                    </div>
                    <div class="we-video-info">
                        <ul>
                            <li>
                                <span class="views" data-toggle="tooltip" title="views">
                                    <i class="fa fa-eye"></i>
                                    <ins>{{$post->count_view}}</ins>
                                </span>
                            </li>
                            <li>
                                <span class="comment" data-toggle="tooltip" title="Comments">
                                    <i class="fa fa-comments-o"></i>
                                    <ins>{{ count($post->children()->get()) }}</ins>
                                </span>
                            </li>
                            <li>
                                <span class="like" data-toggle="tooltip" title="like">
                                    @if (!empty($post->likeable) && $post->likeable->type == 1)
                                        <a href="{{ route('status.like.store', ['statuses_id' => $post->id, 'type' => 2]) }}"><i class="fa fa-heart" style="color: red"></i></a>
                                    @else
                                        <a href="{{ route('status.like.store', ['statuses_id' => $post->id, 'type' => 1]) }}"><i class="ti-heart" style="color: red"></i></a>
                                    @endif
                                    <ins style="color: black">{{$post->count_like}}</ins>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="coment-area">
                <ul class="we-comet">
                    @foreach($post->comments as $comment)
                    <li>
                        <div class="comet-avatar">
                            @if (!empty($comment->image))
                                <img src="{{URL::to("../public/images/".$comment->image)}}" alt="" style="width:60px; height:40px;">
                            @else
                                <img src="{{URL::to("../resources/assets/images/resources/img_user_default.jpg")}}" alt="" style="width:60px; height:40px;">
                            @endif
                        </div>
                        <div class="we-comment">
                            <div class="coment-head">
                                @if ($comment->user->is_anonim == 1)
                                    <h5><a href="time-line.html" title="">{{$comment->user->anonim_name}}*****</a></h5>
                                @else
                                    <h5><a href="time-line.html" title="">{{$comment->user->first_name}} {{$comment->user->last_name}}</a></h5>
                                @endif

                                <span>{{$comment->publish_at}}</span>
                            </div>
                            <p style="width: 100% !important;">
                                {!! nl2br(htmlspecialchars_decode(stripslashes($comment->body))) !!}
                            </p>
                        </div>
                    </li>
                    @endforeach
                    @if (!empty($session))
                        <li class="post-comment">
                            <div class="">
                                <form method="post" action="{{ route('status.comment.store') }}">
                                    <input type="hidden" name="parent_id" value="{{$post->id}}">
                                    <textarea name="body" placeholder="Post your comment" style="border-bottom: 1px solid #eeeeee"></textarea>

                                    <button type="submit">Post</button>
                                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                                </form>
                            </div>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endforeach

resources/views/content/editpost.blade.php
<div class="central-meta">
    <div class="editing-info">
        <h5 class="f-title"><i class="ti-info-alt"></i>Edit Post</h5>
        <form method="post" role="form" action="{{ route('post.edit.store') }}" enctype="multipart/form-data">

            <textarea style="border-bottom: 1px solid #eeeeee !important" name="body" rows="5" placeholder="write something">{{ $post->body }}</textarea>
            <div class="form-radio">
                <div class="radio">
                    <label>
                        <input type="radio" name="status"
                               value="1" {{ $post->status == 1 ? 'checked' : '' }}><i
                                class="check-box"></i>Publish
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="status"
                               value="2" {{ $post->status == 2 ? 'checked' : '' }}><i
                                class="check-box"></i>Unpublish
                    </label>
                </div>
            </div>
            <div class="submit-btns">
                <button type="submit" class="mtr-btn"><span>Save</span></button>
            </div>
            <input type="hidden" name="_token" value="{{ Session::token() }}">
            <input type="hidden" name="id" value="{{ $post->id }}">
        </form>
    </div>
</div>

resources/views/content/editprofile.blade.php
<link rel="stylesheet" href="{{URL::to("../resources/assets/jquery-ui/jquery-ui.min.css")}}">
<link rel="stylesheet" href="https://jqueryui.com/resources/demos/style.css">
<script src="{{URL::to("../resources/assets/js/jquery.js")}}"></script>
<script src="{{URL::to("../resources/assets/jquery-ui/jquery-ui.min.js")}}"></script>

<div class="central-meta">
    <div class="editing-info">
        <h5 class="f-title"><i class="ti-info-alt"></i>Edit Profile Info.</h5>
        @if(Session::get('danger_editprofile'))
            @include('_partials.notifications')
        @endif

        @if(Session::get('success_editprofile'))
            @include('_partials.notifications')
        @endif
        <form method="post" role="form" action="{{ route('profile.edit.store') }}" enctype="multipart/form-data">
            <div class="form-group">
                <input type="text" id="input" required="required" name="name" value="{{ $users->name }}"/>
                <label class="control-label" for="input" name="name">Name</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="text" required="required" name="username" value="{{ $users->username }}"/>
                <label class="control-label" for="input" name="username">Username</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="text" required="required" name="email" value="{{ $users->email }}"/>
                <label class="control-label" for="input"><a href="/cdn-cgi/l/email-protection" class="__cf_email__"
                                                            data-cfemail="abeec6cac2c7eb">Email</a></label><i
                        class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="text" required="required" name="mobile" value="{{ $users->mobile }}"/>
                <label class="control-label" for="input">Mobile</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <input type="text" required="required" name="birth" id="datepicker"
                       value="{{ $users->birth }}"/>
                <label class="control-label" for="input">Tanggal Lahir</label><i class="mtrl-select"></i>
            </div>
            <div class="form-group">
                <label style="color: #078ccd; font-size: 14px; margin-left: 4px;">Image</label>
                <input type="file" name="image" value="{{ $users->image }}"/>
            </div>
            <div class="form-radio">
                <div class="radio">
                    <label>
                        <input type="radio" name="gender"
                               value="2" <?= $users->gender == 2 ? 'checked' : '' ?>><i
                                class="check-box"></i>Male
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="gender"
                               value="1" <?= $users->gender == 1 ? 'checked' : '' ?>><i
                                class="check-box"></i>Female
                    </label>
                </div>
            </div>
            <div class="submit-btns">
                <button type="submit" class="mtr-btn"><span>Save</span></button>
            </div>
            <input type="hidden" name="_token" value="{{ Session::token() }}">
            <input type="hidden" name="id" value="{{ $users->id }}">
        </form>
    </div>
</div>

<script>
    $(function () {
        $("#datepicker").datepicker({
            dateFormat: 'yy-mm-dd',
            changeMonth: true,
            changeYear: true
        });
    });
</script>

resources/views/content/listpost.blade.php
<style>
    .load-comment {
        color: #8c8b8b;
        width: 100%;
        font-size: 13px;
        cursor: pointer;
        text-align: center;
    }

    .load-comment:hover {
        color: #1b78c7;
    }
</style>
@if(count($list_post) > 0)
    @foreach($list_post as $post)
        <div class="central-meta item">
            <div class="user-post">
                <div class="friend-info">
                    <figure>
                        @if (!empty($post->image))
                            <img src="{{URL::to("../public/images/".$post->image)}}" alt=""
                                 style="width:60px; height:60px;">
                        @else
                            <img src="{{URL::to("../resources/assets/images/resources/img_user_default.jpg")}}" alt=""
                                 style="width:60px; height:60px;">
                        @endif
                    </figure>
                    <div class="friend-name">
                        @if ($post->user->is_anonim == 1)
                            <ins><a title="">{{$post->user->anonim_name}}*****</a></ins>
                        @else
                            <ins><a title="">{{$post->user->first_name}} {{$post->user->last_name}}</a></ins>
                        @endif
                        <span>published: {{$post->publish_at}}</span>
                    </div>
                    <div class="post-meta">

                        <div class="description">
                            <p>
                                {!! nl2br(htmlspecialchars_decode(stripslashes($post->body_limit_20))) !!}
                                <br>
                                <a href="{{URL::to('/post/'.base64_encode($post->id))}}" style="color:#088dcd">Read
                                    More</a>
                            </p>
                        </div>
                        <div class="we-video-info">
                            <ul>
                                <li>
                                <span class="views" data-toggle="tooltip" title="views">
                                    <i class="fa fa-eye"></i>
                                    <ins>{{$post->count_view}}</ins>
                                </span>
                                </li>
                                <li>
                                <span class="comment" data-toggle="tooltip" title="Comments">
                                    <a href="{{URL::to('/post/'.base64_encode($post->id))}}"><i
                                                class="fa fa-comments-o"></i></a>
                                    <ins>{{ count($post->children()->get()) }}</ins>
                                </span>
                                </li>

                                <li>
                                <span class="like" data-toggle="tooltip" title="like">
                                    @if (!empty($session))
                                        @if (!empty($post->likeable) && $post->has_like == 1)
                                            <a href="{{ route('status.like.store', ['statuses_id' => $post->id, 'type' => 2]) }}"><i
                                                        class="fa fa-heart" style="color: red"></i></a>
                                        @else
                                            <a href="{{ route('status.like.store', ['statuses_id' => $post->id, 'type' => 1]) }}"><i
                                                        class="ti-heart" style="color: red"></i></a>
                                        @endif
                                    @else
                                        <a><i class="fa fa-heart" style="color: red"></i></a>
                                    @endif
                                    <ins style="color: black">{{$post->count_like}}</ins>
                                </span>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>

                <div class="coment-area">
                    <ul class="we-comet">
                        @foreach($post->comment_limit as $comment)
                            <li>
                                <div class="comet-avatar">
                                    @if (!empty($comment->image))
                                        <img src="{{URL::to("../public/images/".$comment->image)}}" alt="image"
                                             style="width:60px; height:40px;">
                                    @else
                                        <img src="{{URL::to("../resources/assets/images/resources/img_user_default.jpg")}}"
                                             alt="image" style="width:60px; height:40px;">
                                    @endif
                                </div>
                                <div class="we-comment">
                                    <div class="coment-head">
                                        @if ($comment->user->is_anonim == 1)
                                            <h5><a title="">{{$comment->user->anonim_name}}
                                                    *****</a>
                                            </h5>
                                        @else
                                            <h5><a title="">{{$comment->user->first_name}} {{$comment->user->last_name}}</a>
                                            </h5>
                                        @endif
                                        <span>{{$comment->publish_at}}</span>
                                    </div>
                                    <p style="width: 100% !important;">
                                        {!! nl2br(htmlspecialchars_decode(stripslashes($comment->body))) !!}
                                    </p>
                                </div>
                            </li>
                        @endforeach
                        @if(count($post->children()->get()) > 3)
                            <li>
                                <div class="load-comment">
                                    <a href="{{URL::to('/post/'.base64_encode($post->id))}}">Load more comment</a>
                                </div>
                            </li>
                        @endif
                        @if (!empty($session))
                            <li class="post-comment">
                                <div class="">
                                    <form method="post" action="{{ route('status.comment.store') }}">
                                        <input type="hidden" name="parent_id" value="{{$post->id}}">
                                        <textarea name="body" placeholder="Post your comment"
                                                  style="border-bottom: 1px solid #eeeeee"></textarea>

                                        <button type="submit">Post</button>
                                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                                    </form>
                                </div>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    @endforeach
@else
    @include('_partials.norecord')
@endif
<?php
use App\Helpers\Helper;
$page = 2;
if (isset($_GET['page'])) {
    $page = $_GET['page'] + 1;
}
$currentRoute = \App\Helpers\Helper::getCurrentRoute();
?>
@if(count($all_list_post)>10)
    <a href="{{URL::to($currentRoute."?page=".$page)}}">
        <button class="btn-view btn-load-more"></button>
    </a>
@endif

resources/views/content/mostpopular.blade.php
<div class="widget stick-widget">
    <h4 class="widget-title">Most Popular Post</h4>
    <ul class="short-profile">
        @if(count($popular_post) > 0)
            @foreach($popular_post as $post)
                <li class="pointing">
                    <span>{{$post->user->first_name}} {{$post->user->last_name}}</span>
                    <p>
                        {!! nl2br(htmlspecialchars_decode(stripslashes(str_limit(strip_tags($post->body), 50)))) !!}
                        <a href="{{URL::to('/post/'.base64_encode($post->id))}}"><span
                                    style="color: #1b78c7">Read More</span></a>
                    </p>
                </li>
            @endforeach
        @else
            Data Not Found
        @endif
    </ul>
</div>

resources/views/content/summarypost.blade.php
<div class="widget">
    <h4 class="widget-title">Your page</h4>
    <div class="your-page">
        <div class="page-likes">
            <ul class="nav nav-tabs likes-btn">
                <li class="nav-item"><a class="active" href="#link1" data-toggle="tab">likes</a></li>
                <li class="nav-item"><a class="" href="#link2" data-toggle="tab">views</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active fade show " id="link1">
                    <span><i class="ti-heart"></i>{{ $like_visitable['like']  }}</span>
                    <a href="#" title="weekly-likes">{{ $like_visitable['like_this_week'] }} new likes this week</a>
                </div>
                <div class="tab-pane fade" id="link2">
                    <span><i class="ti-eye"></i>{{ $like_visitable['visitable']  }}</span>
                    <a href="#" title="weekly-likes">{{ $like_visitable['visitable_this_week'] }} new views this
                        week</a>
                </div>
            </div>
        </div>
    </div>
</div><!-- page like widget -->

resources/views/content/writepost.blade.php
@if (!empty($session))
<div class="central-meta new-pst">
    <div class="new-postbox">
        <figure>
            @if (!empty($users->image))
                <img src="{{URL::to("../public/images/".$users->image)}}" alt="" style="width:60px; height:60px;">
            @else
                <img src="{{URL::to("../resources/assets/images/resources/img_user_default.jpg")}}" alt=""
                     style="width:60px; height:60px;">
            @endif
        </figure>
        <div class="newpst-input">
            <form method="post" action="{{ route('status.post.store') }}">
                <textarea name="body" rows="2" placeholder="write something"></textarea>
                <div class="attachments">
                    <ul>
                        <li>
                            <button type="submit">Post</button>
                        </li>
                    </ul>
                </div>
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </form>
        </div>
    </div>
</div><!-- add post new box -->
@endif